[package]
name = "ed_ed"
version = "0.1.0"
authors = ["J0eCool <count.j0ecool@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.28"
gl = "0.14.0"
sdl2 = "0.34"
wasmtime = "0.16"
